export const sp500 = [
  { company: "Apple Inc.", symbol: "AAPL", weight: "6.374682" },
  { company: "Microsoft Corporation", symbol: "MSFT", weight: "6.365421" },
  { company: "Amazon.com Inc.", symbol: "AMZN", weight: "3.908939" },
  { company: "Tesla Inc", symbol: "TSLA", weight: "2.269981" },
  { company: "Alphabet Inc. Class A", symbol: "GOOGL", weight: "2.205572" },
  { company: "Alphabet Inc. Class C", symbol: "GOOG", weight: "2.072442" },
  { company: "NVIDIA Corporation", symbol: "NVDA", weight: "2.041043" },
  { company: "Meta Platforms Inc. Class A", symbol: "FB", weight: "2.038007" },
  {
    company: "Berkshire Hathaway Inc. Class B",
    symbol: "BRK-B",
    weight: "1.334875",
  },
  { company: "JPMorgan Chase & Co.", symbol: "JPM", weight: "1.250684" },
  { company: "Home Depot Inc.", symbol: "HD", weight: "1.098458" },
  {
    company: "UnitedHealth Group Incorporated",
    symbol: "UNH",
    weight: "1.064096",
  },
  { company: "Johnson & Johnson", symbol: "JNJ", weight: "1.057471" },
  { company: "Procter & Gamble Company", symbol: "PG", weight: "0.904632" },
  { company: "Bank of America Corp", symbol: "BAC", weight: "0.88419" },
  { company: "Visa Inc. Class A", symbol: "V", weight: "0.859888" },
  { company: "Adobe Inc.", symbol: "ADBE", weight: "0.798147" },
  {
    company: "Mastercard Incorporated Class A",
    symbol: "MA",
    weight: "0.742526",
  },
  { company: "Netflix Inc.", symbol: "NFLX", weight: "0.730395" },
  { company: "Pfizer Inc.", symbol: "PFE", weight: "0.715271" },
  { company: "salesforce.com inc.", symbol: "CRM", weight: "0.704273" },
  { company: "Walt Disney Company", symbol: "DIS", weight: "0.689397" },
  { company: "Exxon Mobil Corporation", symbol: "XOM", weight: "0.673713" },
  { company: "Thermo Fisher Scientific Inc.", symbol: "TMO", weight: "0.6243" },
  {
    company: "Costco Wholesale Corporation",
    symbol: "COST",
    weight: "0.609339",
  },
  {
    company: "Comcast Corporation Class A",
    symbol: "CMCSA",
    weight: "0.595698",
  },
  { company: "Cisco Systems Inc.", symbol: "CSCO", weight: "0.586753" },
  { company: "Accenture Plc Class A", symbol: "ACN", weight: "0.576062" },
  { company: "Broadcom Inc.", symbol: "AVGO", weight: "0.574734" },
  { company: "Chevron Corporation", symbol: "CVX", weight: "0.568326" },
  { company: "PepsiCo Inc.", symbol: "PEP", weight: "0.567418" },
  { company: "PayPal Holdings Inc.", symbol: "PYPL", weight: "0.555871" },
  { company: "Abbott Laboratories", symbol: "ABT", weight: "0.555837" },
  { company: "NIKE Inc. Class B", symbol: "NKE", weight: "0.551364" },
  { company: "Coca-Cola Company", symbol: "KO", weight: "0.539935" },
  { company: "Verizon Communications Inc.", symbol: "VZ", weight: "0.536259" },
  { company: "Wells Fargo & Company", symbol: "WFC", weight: "0.528377" },
  { company: "AbbVie Inc.", symbol: "ABBV", weight: "0.525841" },
  { company: "Walmart Inc.", symbol: "WMT", weight: "0.525163" },
  { company: "Merck & Co. Inc.", symbol: "MRK", weight: "0.522228" },
  { company: "Eli Lilly and Company", symbol: "LLY", weight: "0.521651" },
  { company: "Qualcomm Inc", symbol: "QCOM", weight: "0.511173" },
  { company: "Intel Corporation", symbol: "INTC", weight: "0.506249" },
  { company: "Danaher Corporation", symbol: "DHR", weight: "0.502659" },
  { company: "McDonald's Corporation", symbol: "MCD", weight: "0.481498" },
  { company: "Advanced Micro Devices Inc.", symbol: "AMD", weight: "0.479991" },
  { company: "Intuit Inc.", symbol: "INTU", weight: "0.468729" },
  {
    company: "Texas Instruments Incorporated",
    symbol: "TXN",
    weight: "0.448211",
  },
  { company: "Lowe's Companies Inc.", symbol: "LOW", weight: "0.447829" },
  { company: "AT&T Inc.", symbol: "T", weight: "0.438134" },
  { company: "NextEra Energy Inc.", symbol: "NEE", weight: "0.429035" },
  { company: "Linde plc", symbol: "LIN", weight: "0.423794" },
  { company: "Union Pacific Corporation", symbol: "UNP", weight: "0.403275" },
  { company: "Oracle Corporation", symbol: "ORCL", weight: "0.38657" },
  { company: "Medtronic Plc", symbol: "MDT", weight: "0.385677" },
  {
    company: "United Parcel Service Inc. Class B",
    symbol: "UPS",
    weight: "0.380746",
  },
  { company: "Morgan Stanley", symbol: "MS", weight: "0.370138" },
  {
    company: "Honeywell International Inc.",
    symbol: "HON",
    weight: "0.367404",
  },
  {
    company: "Philip Morris International Inc.",
    symbol: "PM",
    weight: "0.351869",
  },
  { company: "Citigroup Inc.", symbol: "C", weight: "0.341956" },
  { company: "Applied Materials Inc.", symbol: "AMAT", weight: "0.341535" },
  { company: "Goldman Sachs Group Inc.", symbol: "GS", weight: "0.337453" },
  { company: "Starbucks Corporation", symbol: "SBUX", weight: "0.336992" },
  { company: "BlackRock Inc.", symbol: "BLK", weight: "0.33339" },
  {
    company: "Raytheon Technologies Corporation",
    symbol: "RTX",
    weight: "0.329694",
  },
  { company: "ServiceNow Inc.", symbol: "NOW", weight: "0.32257" },
  {
    company: "Bristol-Myers Squibb Company",
    symbol: "BMY",
    weight: "0.316565",
  },
  { company: "Charles Schwab Corporation", symbol: "SCHW", weight: "0.31299" },
  { company: "Target Corporation", symbol: "TGT", weight: "0.308612" },
  { company: "CVS Health Corporation", symbol: "CVS", weight: "0.306592" },
  { company: "Intuitive Surgical Inc.", symbol: "ISRG", weight: "0.303233" },
  { company: "American Tower Corporation", symbol: "AMT", weight: "0.30301" },
  { company: "Boeing Company", symbol: "BA", weight: "0.290975" },
  { company: "Amgen Inc.", symbol: "AMGN", weight: "0.290457" },
  { company: "Prologis Inc.", symbol: "PLD", weight: "0.286435" },
  { company: "Caterpillar Inc.", symbol: "CAT", weight: "0.284288" },
  { company: "General Electric Company", symbol: "GE", weight: "0.281393" },
  { company: "S&P Global Inc.", symbol: "SPGI", weight: "0.28011" },
  { company: "American Express Company", symbol: "AXP", weight: "0.276922" },
  { company: "Zoetis Inc. Class A", symbol: "ZTS", weight: "0.265245" },
  {
    company: "International Business Machines Corporation",
    symbol: "IBM",
    weight: "0.262377",
  },
  { company: "Deere & Company", symbol: "DE", weight: "0.261857" },
  { company: "Anthem Inc.", symbol: "ANTM", weight: "0.259723" },
  { company: "3M Company", symbol: "MMM", weight: "0.257748" },
  { company: "ConocoPhillips", symbol: "COP", weight: "0.251281" },
  {
    company: "Automatic Data Processing Inc.",
    symbol: "ADP",
    weight: "0.248664",
  },
  { company: "Analog Devices Inc.", symbol: "ADI", weight: "0.246129" },
  { company: "Micron Technology Inc.", symbol: "MU", weight: "0.243376" },
  { company: "Moderna Inc.", symbol: "MRNA", weight: "0.240756" },
  { company: "Booking Holdings Inc.", symbol: "BKNG", weight: "0.239237" },
  { company: "Lam Research Corporation", symbol: "LRCX", weight: "0.236125" },
  { company: "General Motors Company", symbol: "GM", weight: "0.226403" },
  {
    company: "PNC Financial Services Group Inc.",
    symbol: "PNC",
    weight: "0.222338",
  },
  { company: "Gilead Sciences Inc.", symbol: "GILD", weight: "0.220313" },
  { company: "TJX Companies Inc", symbol: "TJX", weight: "0.216264" },
  {
    company: "Marsh & McLennan Companies Inc.",
    symbol: "MMC",
    weight: "0.215704",
  },
  {
    company: "Mondelez International Inc. Class A",
    symbol: "MDLZ",
    weight: "0.214948",
  },
  { company: "Stryker Corporation", symbol: "SYK", weight: "0.214742" },
  {
    company: "Charter Communications Inc. Class A",
    symbol: "CHTR",
    weight: "0.213974",
  },
  { company: "Lockheed Martin Corporation", symbol: "LMT", weight: "0.212272" },
  {
    company: "Truist Financial Corporation",
    symbol: "TFC",
    weight: "0.210519",
  },
  { company: "Chubb Limited", symbol: "CB", weight: "0.209501" },
  { company: "CME Group Inc. Class A", symbol: "CME", weight: "0.206184" },
  { company: "CSX Corporation", symbol: "CSX", weight: "0.204941" },
  { company: "Altria Group Inc", symbol: "MO", weight: "0.203846" },
  {
    company: "Estee Lauder Companies Inc. Class A",
    symbol: "EL",
    weight: "0.203076",
  },
  { company: "U.S. Bancorp", symbol: "USB", weight: "0.202461" },
  {
    company: "Crown Castle International Corp",
    symbol: "CCI",
    weight: "0.202306",
  },
  { company: "Ford Motor Company", symbol: "F", weight: "0.199259" },
  { company: "Sherwin-Williams Company", symbol: "SHW", weight: "0.198518" },
  { company: "Duke Energy Corporation", symbol: "DUK", weight: "0.193274" },
  {
    company: "Intercontinental Exchange Inc.",
    symbol: "ICE",
    weight: "0.186794",
  },
  { company: "Cigna Corporation", symbol: "CI", weight: "0.179599" },
  { company: "Equinix Inc.", symbol: "EQIX", weight: "0.179507" },
  {
    company: "Edwards Lifesciences Corporation",
    symbol: "EW",
    weight: "0.178961",
  },
  {
    company: "Becton Dickinson and Company",
    symbol: "BDX",
    weight: "0.176055",
  },
  {
    company: "Capital One Financial Corporation",
    symbol: "COF",
    weight: "0.174363",
  },
  { company: "Illinois Tool Works Inc.", symbol: "ITW", weight: "0.173769" },
  {
    company: "Norfolk Southern Corporation",
    symbol: "NSC",
    weight: "0.172041",
  },
  { company: "Eaton Corp. Plc", symbol: "ETN", weight: "0.170878" },
  {
    company: "Regeneron Pharmaceuticals Inc.",
    symbol: "REGN",
    weight: "0.170841",
  },
  {
    company: "Fidelity National Information Services Inc.",
    symbol: "FIS",
    weight: "0.17017",
  },
  { company: "Aon Plc Class A", symbol: "AON", weight: "0.169116" },
  { company: "T-Mobile US Inc.", symbol: "TMUS", weight: "0.168388" },
  { company: "Southern Company", symbol: "SO", weight: "0.167548" },
  {
    company: "Air Products and Chemicals Inc.",
    symbol: "APD",
    weight: "0.165336",
  },
  { company: "Colgate-Palmolive Company", symbol: "CL", weight: "0.164485" },
  { company: "Waste Management Inc.", symbol: "WM", weight: "0.161004" },
  { company: "Moody's Corporation", symbol: "MCO", weight: "0.159395" },
  { company: "KLA Corporation", symbol: "KLAC", weight: "0.158294" },
  { company: "Dominion Energy Inc", symbol: "D", weight: "0.151854" },
  { company: "FedEx Corporation", symbol: "FDX", weight: "0.150361" },
  { company: "Fiserv Inc.", symbol: "FISV", weight: "0.148425" },
  { company: "HCA Healthcare Inc", symbol: "HCA", weight: "0.148269" },
  { company: "NXP Semiconductors NV", symbol: "NXPI", weight: "0.146958" },
  {
    company: "Boston Scientific Corporation",
    symbol: "BSX",
    weight: "0.145323",
  },
  { company: "DexCom Inc.", symbol: "DXCM", weight: "0.14518" },
  { company: "Ecolab Inc.", symbol: "ECL", weight: "0.144401" },
  { company: "Xilinx Inc.", symbol: "XLNX", weight: "0.142851" },
  { company: "Freeport-McMoRan Inc.", symbol: "FCX", weight: "0.142335" },
  { company: "Autodesk Inc.", symbol: "ADSK", weight: "0.141738" },
  { company: "Emerson Electric Co.", symbol: "EMR", weight: "0.141261" },
  {
    company: "Johnson Controls International plc",
    symbol: "JCI",
    weight: "0.140903",
  },
  { company: "Humana Inc.", symbol: "HUM", weight: "0.140562" },
  { company: "Progressive Corporation", symbol: "PGR", weight: "0.140347" },
  { company: "Simon Property Group Inc.", symbol: "SPG", weight: "0.139291" },
  {
    company: "Northrop Grumman Corporation",
    symbol: "NOC",
    weight: "0.136384",
  },
  { company: "EOG Resources Inc.", symbol: "EOG", weight: "0.136238" },
  { company: "Illumina Inc.", symbol: "ILMN", weight: "0.134461" },
  { company: "Exelon Corporation", symbol: "EXC", weight: "0.133665" },
  { company: "Synopsys Inc.", symbol: "SNPS", weight: "0.133611" },
  { company: "MSCI Inc. Class A", symbol: "MSCI", weight: "0.132869" },
  { company: "IDEXX Laboratories Inc.", symbol: "IDXX", weight: "0.132795" },
  { company: "Dollar General Corporation", symbol: "DG", weight: "0.132344" },
  { company: "TE Connectivity Ltd.", symbol: "TEL", weight: "0.131899" },
  { company: "IHS Markit Ltd.", symbol: "INFO", weight: "0.129729" },
  { company: "Roper Technologies Inc.", symbol: "ROP", weight: "0.128182" },
  { company: "Public Storage", symbol: "PSA", weight: "0.128068" },
  { company: "IQVIA Holdings Inc", symbol: "IQV", weight: "0.127489" },
  {
    company: "Cadence Design Systems Inc.",
    symbol: "CDNS",
    weight: "0.127335",
  },
  {
    company: "Amphenol Corporation Class A",
    symbol: "APH",
    weight: "0.126457",
  },
  {
    company: "American International Group Inc.",
    symbol: "AIG",
    weight: "0.124149",
  },
  { company: "Carrier Global Corp.", symbol: "CARR", weight: "0.121177" },
  {
    company: "Vertex Pharmaceuticals Incorporated",
    symbol: "VRTX",
    weight: "0.121162",
  },
  { company: "Chipotle Mexican Grill Inc.", symbol: "CMG", weight: "0.12035" },
  { company: "Activision Blizzard Inc.", symbol: "ATVI", weight: "0.118793" },
  { company: "Align Technology Inc.", symbol: "ALGN", weight: "0.118748" },
  { company: "T. Rowe Price Group", symbol: "TROW", weight: "0.118203" },
  { company: "Digital Realty Trust Inc.", symbol: "DLR", weight: "0.117745" },
  {
    company: "Bank of New York Mellon Corporation",
    symbol: "BK",
    weight: "0.117335",
  },
  { company: "Trane Technologies plc", symbol: "TT", weight: "0.116467" },
  { company: "Agilent Technologies Inc.", symbol: "A", weight: "0.116403" },
  { company: "eBay Inc.", symbol: "EBAY", weight: "0.116148" },
  {
    company: "Microchip Technology Incorporated",
    symbol: "MCHP",
    weight: "0.115326",
  },
  { company: "General Dynamics Corporation", symbol: "GD", weight: "0.115033" },
  { company: "Aptiv PLC", symbol: "APTV", weight: "0.11502" },
  { company: "MetLife Inc.", symbol: "MET", weight: "0.114396" },
  { company: "Kimberly-Clark Corporation", symbol: "KMB", weight: "0.114201" },
  { company: "Fortinet Inc.", symbol: "FTNT", weight: "0.113276" },
  { company: "O'Reilly Automotive Inc.", symbol: "ORLY", weight: "0.111787" },
  { company: "Newmont Corporation", symbol: "NEM", weight: "0.111161" },
  { company: "Motorola Solutions Inc.", symbol: "MSI", weight: "0.110954" },
  { company: "Centene Corporation", symbol: "CNC", weight: "0.11055" },
  { company: "L3Harris Technologies Inc", symbol: "LHX", weight: "0.110226" },
  { company: "Schlumberger NV", symbol: "SLB", weight: "0.11015" },
  { company: "Dow Inc.", symbol: "DOW", weight: "0.109649" },
  { company: "SVB Financial Group", symbol: "SIVB", weight: "0.108939" },
  {
    company: "Pioneer Natural Resources Company",
    symbol: "PXD",
    weight: "0.108246",
  },
  {
    company: "Marriott International Inc. Class A",
    symbol: "MAR",
    weight: "0.108116",
  },
  { company: "HP Inc.", symbol: "HPQ", weight: "0.10676" },
  {
    company: "Cognizant Technology Solutions Corporation Class A",
    symbol: "CTSH",
    weight: "0.106423",
  },
  { company: "Prudential Financial Inc.", symbol: "PRU", weight: "0.106047" },
  {
    company: "American Electric Power Company Inc.",
    symbol: "AEP",
    weight: "0.105191",
  },
  { company: "Parker-Hannifin Corporation", symbol: "PH", weight: "0.105189" },
  { company: "Ross Stores Inc.", symbol: "ROST", weight: "0.103445" },
  {
    company: "Marathon Petroleum Corporation",
    symbol: "MPC",
    weight: "0.103306",
  },
  { company: "DuPont de Nemours Inc.", symbol: "DD", weight: "0.103229" },
  {
    company: "Hilton Worldwide Holdings Inc",
    symbol: "HLT",
    weight: "0.101526",
  },
  { company: "Paychex Inc.", symbol: "PAYX", weight: "0.10045" },
  { company: "Rockwell Automation Inc.", symbol: "ROK", weight: "0.100364" },
  { company: "AutoZone Inc.", symbol: "AZO", weight: "0.10022" },
  { company: "Sempra Energy", symbol: "SRE", weight: "0.099984" },
  { company: "Travelers Companies Inc.", symbol: "TRV", weight: "0.099444" },
  {
    company: "Constellation Brands Inc. Class A",
    symbol: "STZ",
    weight: "0.098096",
  },
  { company: "Sysco Corporation", symbol: "SYY", weight: "0.097924" },
  { company: "Realty Income Corporation", symbol: "O", weight: "0.09739" },
  {
    company: "SBA Communications Corp. Class A",
    symbol: "SBAC",
    weight: "0.097388",
  },
  { company: "Baxter International Inc.", symbol: "BAX", weight: "0.097303" },
  { company: "Cintas Corporation", symbol: "CTAS", weight: "0.096893" },
  { company: "First Republic Bank", symbol: "FRC", weight: "0.096352" },
  { company: "General Mills Inc.", symbol: "GIS", weight: "0.096227" },
  { company: "Match Group Inc.", symbol: "MTCH", weight: "0.095375" },
  { company: "Twitter Inc.", symbol: "TWTR", weight: "0.095088" },
  { company: "PPG Industries Inc.", symbol: "PPG", weight: "0.0945" },
  { company: "Yum! Brands Inc.", symbol: "YUM", weight: "0.09406" },
  { company: "Biogen Inc.", symbol: "BIIB", weight: "0.093465" },
  { company: "ResMed Inc.", symbol: "RMD", weight: "0.093058" },
  {
    company: "Archer-Daniels-Midland Company",
    symbol: "ADM",
    weight: "0.093029",
  },
  { company: "Verisk Analytics Inc", symbol: "VRSK", weight: "0.092303" },
  { company: "Keysight Technologies Inc", symbol: "KEYS", weight: "0.09224" },
  {
    company: "International Flavors & Fragrances Inc.",
    symbol: "IFF",
    weight: "0.092109",
  },
  { company: "Welltower Inc.", symbol: "WELL", weight: "0.091796" },
  { company: "Global Payments Inc.", symbol: "GPN", weight: "0.091756" },
  { company: "Otis Worldwide Corporation", symbol: "OTIS", weight: "0.090395" },
  { company: "Electronic Arts Inc.", symbol: "EA", weight: "0.090371" },
  { company: "Etsy Inc.", symbol: "ETSY", weight: "0.090324" },
  { company: "State Street Corporation", symbol: "STT", weight: "0.090089" },
  { company: "Discover Financial Services", symbol: "DFS", weight: "0.089731" },
  { company: "Xcel Energy Inc.", symbol: "XEL", weight: "0.088509" },
  { company: "Aflac Incorporated", symbol: "AFL", weight: "0.088209" },
  {
    company: "Mettler-Toledo International Inc.",
    symbol: "MTD",
    weight: "0.087945",
  },
  { company: "CBRE Group Inc. Class A", symbol: "CBRE", weight: "0.087763" },
  { company: "Fastenal Company", symbol: "FAST", weight: "0.087761" },
  { company: "McKesson Corporation", symbol: "MCK", weight: "0.087636" },
  { company: "Corteva Inc", symbol: "CTVA", weight: "0.087583" },
  { company: "Williams Companies Inc.", symbol: "WMB", weight: "0.086985" },
  { company: "Equifax Inc.", symbol: "EFX", weight: "0.0866" },
  { company: "AvalonBay Communities Inc.", symbol: "AVB", weight: "0.086429" },
  { company: "Ameriprise Financial Inc.", symbol: "AMP", weight: "0.086242" },
  { company: "Arthur J. Gallagher & Co.", symbol: "AJG", weight: "0.086202" },
  { company: "Enphase Energy Inc.", symbol: "ENPH", weight: "0.086118" },
  { company: "Dollar Tree Inc.", symbol: "DLTR", weight: "0.085279" },
  { company: "Nucor Corporation", symbol: "NUE", weight: "0.085251" },
  { company: "ANSYS Inc.", symbol: "ANSS", weight: "0.085186" },
  { company: "Allstate Corporation", symbol: "ALL", weight: "0.08504" },
  {
    company: "Old Dominion Freight Line Inc.",
    symbol: "ODFL",
    weight: "0.084385",
  },
  {
    company: "Walgreens Boots Alliance Inc",
    symbol: "WBA",
    weight: "0.083932",
  },
  {
    company: "Monster Beverage Corporation",
    symbol: "MNST",
    weight: "0.08321",
  },
  { company: "AMETEK Inc.", symbol: "AME", weight: "0.082965" },
  { company: "D.R. Horton Inc.", symbol: "DHI", weight: "0.082629" },
  {
    company: "Public Service Enterprise Group Inc",
    symbol: "PEG",
    weight: "0.08189",
  },
  { company: "Cummins Inc.", symbol: "CMI", weight: "0.081326" },
  {
    company: "TransDigm Group Incorporated",
    symbol: "TDG",
    weight: "0.081136",
  },
  { company: "Phillips 66", symbol: "PSX", weight: "0.081124" },
  { company: "Kinder Morgan Inc Class P", symbol: "KMI", weight: "0.080749" },
  { company: "Albemarle Corporation", symbol: "ALB", weight: "0.08049" },
  {
    company: "West Pharmaceutical Services Inc.",
    symbol: "WST",
    weight: "0.080473",
  },
  {
    company: "Zebra Technologies Corporation Class A",
    symbol: "ZBRA",
    weight: "0.080093",
  },
  {
    company: "American Water Works Company Inc.",
    symbol: "AWK",
    weight: "0.078921",
  },
  { company: "Copart Inc.", symbol: "CPRT", weight: "0.078006" },
  { company: "PACCAR Inc", symbol: "PCAR", weight: "0.077239" },
  { company: "Fifth Third Bancorp", symbol: "FITB", weight: "0.077227" },
  { company: "Stanley Black & Decker Inc.", symbol: "SWK", weight: "0.077097" },
  { company: "Ball Corporation", symbol: "BLL", weight: "0.076678" },
  {
    company: "Willis Towers Watson Public Limited Company",
    symbol: "WLTW",
    weight: "0.076412",
  },
  { company: "Lennar Corporation Class A", symbol: "LEN", weight: "0.075602" },
  { company: "Corning Inc", symbol: "GLW", weight: "0.07525" },
  { company: "Equity Residential", symbol: "EQR", weight: "0.075044" },
  { company: "Valero Energy Corporation", symbol: "VLO", weight: "0.074789" },
  { company: "Weyerhaeuser Company", symbol: "WY", weight: "0.073282" },
  { company: "Eversource Energy", symbol: "ES", weight: "0.073188" },
  {
    company: "Alexandria Real Estate Equities Inc.",
    symbol: "ARE",
    weight: "0.072986",
  },
  { company: "Republic Services Inc.", symbol: "RSG", weight: "0.072924" },
  { company: "Kroger Co.", symbol: "KR", weight: "0.07253" },
  { company: "ONEOK Inc.", symbol: "OKE", weight: "0.07243" },
  { company: "WEC Energy Group Inc", symbol: "WEC", weight: "0.071738" },
  {
    company: "Occidental Petroleum Corporation",
    symbol: "OXY",
    weight: "0.071205",
  },
  { company: "Devon Energy Corporation", symbol: "DVN", weight: "0.071191" },
  { company: "Synchrony Financial", symbol: "SYF", weight: "0.0711" },
  { company: "Arista Networks Inc.", symbol: "ANET", weight: "0.070727" },
  { company: "Fortive Corp.", symbol: "FTV", weight: "0.070129" },
  { company: "Southwest Airlines Co.", symbol: "LUV", weight: "0.069718" },
  { company: "Kansas City Southern", symbol: "KSU", weight: "0.069369" },
  { company: "Generac Holdings Inc.", symbol: "GNRC", weight: "0.069169" },
  { company: "CDW Corp.", symbol: "CDW", weight: "0.06886" },
  {
    company: "Laboratory Corporation of America Holdings",
    symbol: "LH",
    weight: "0.06878",
  },
  { company: "Extra Space Storage Inc.", symbol: "EXR", weight: "0.068555" },
  { company: "Consolidated Edison Inc.", symbol: "ED", weight: "0.068527" },
  { company: "Gartner Inc.", symbol: "IT", weight: "0.068384" },
  { company: "Zimmer Biomet Holdings Inc.", symbol: "ZBH", weight: "0.068198" },
  { company: "United Rentals Inc.", symbol: "URI", weight: "0.067858" },
  { company: "Vulcan Materials Company", symbol: "VMC", weight: "0.067174" },
  {
    company: "Martin Marietta Materials Inc.",
    symbol: "MLM",
    weight: "0.066162",
  },
  { company: "Hershey Company", symbol: "HSY", weight: "0.065999" },
  { company: "Best Buy Co. Inc.", symbol: "BBY", weight: "0.065763" },
  { company: "Skyworks Solutions Inc.", symbol: "SWKS", weight: "0.065034" },
  { company: "Northern Trust Corporation", symbol: "NTRS", weight: "0.06498" },
  { company: "Tractor Supply Company", symbol: "TSCO", weight: "0.064749" },
  { company: "Delta Air Lines Inc.", symbol: "DAL", weight: "0.063684" },
  { company: "Dover Corporation", symbol: "DOV", weight: "0.063631" },
  { company: "Expedia Group Inc.", symbol: "EXPE", weight: "0.063116" },
  { company: "Edison International", symbol: "EIX", weight: "0.06298" },
  { company: "Kraft Heinz Company", symbol: "KHC", weight: "0.062593" },
  {
    company: "Hartford Financial Services Group Inc.",
    symbol: "HIG",
    weight: "0.062247",
  },
  { company: "Ingersoll Rand Inc.", symbol: "IR", weight: "0.061999" },
  { company: "Tyson Foods Inc. Class A", symbol: "TSN", weight: "0.06154" },
  { company: "V.F. Corporation", symbol: "VFC", weight: "0.061325" },
  {
    company: "Mid-America Apartment Communities Inc.",
    symbol: "MAA",
    weight: "0.060827",
  },
  { company: "Nasdaq Inc.", symbol: "NDAQ", weight: "0.06077" },
  {
    company: "Huntington Bancshares Incorporated",
    symbol: "HBAN",
    weight: "0.060533",
  },
  { company: "CarMax Inc.", symbol: "KMX", weight: "0.060189" },
  { company: "VeriSign Inc.", symbol: "VRSN", weight: "0.059877" },
  {
    company: "LyondellBasell Industries NV",
    symbol: "LYB",
    weight: "0.059495",
  },
  {
    company: "Monolithic Power Systems Inc.",
    symbol: "MPWR",
    weight: "0.059261",
  },
  { company: "Teradyne Inc.", symbol: "TER", weight: "0.058904" },
  {
    company: "Regions Financial Corporation",
    symbol: "RF",
    weight: "0.058837",
  },
  { company: "Essex Property Trust Inc.", symbol: "ESS", weight: "0.058258" },
  { company: "Church & Dwight Co. Inc.", symbol: "CHD", weight: "0.057479" },
  { company: "KeyCorp", symbol: "KEY", weight: "0.057462" },
  { company: "Pool Corporation", symbol: "POOL", weight: "0.057158" },
  { company: "Duke Realty Corporation", symbol: "DRE", weight: "0.056558" },
  { company: "Xylem Inc.", symbol: "XYL", weight: "0.056492" },
  { company: "Hess Corporation", symbol: "HES", weight: "0.056363" },
  { company: "Ulta Beauty Inc", symbol: "ULTA", weight: "0.056244" },
  { company: "STERIS Plc", symbol: "STE", weight: "0.056115" },
  { company: "Ameren Corporation", symbol: "AEE", weight: "0.055409" },
  { company: "Catalent Inc", symbol: "CTLT", weight: "0.055356" },
  { company: "PPL Corporation", symbol: "PPL", weight: "0.055306" },
  { company: "W.W. Grainger Inc.", symbol: "GWW", weight: "0.054665" },
  {
    company: "Citizens Financial Group Inc.",
    symbol: "CFG",
    weight: "0.054518",
  },
  { company: "Paycom Software Inc.", symbol: "PAYC", weight: "0.054513" },
  { company: "DTE Energy Company", symbol: "DTE", weight: "0.054505" },
  { company: "Cerner Corporation", symbol: "CERN", weight: "0.054459" },
  { company: "Trimble Inc.", symbol: "TRMB", weight: "0.05439" },
  {
    company: "Expeditors International of Washington Inc.",
    symbol: "EXPD",
    weight: "0.054056",
  },
  { company: "Garmin Ltd.", symbol: "GRMN", weight: "0.05402" },
  { company: "Entergy Corporation", symbol: "ETR", weight: "0.053601" },
  {
    company: "McCormick & Company Incorporated",
    symbol: "MKC",
    weight: "0.053415",
  },
  { company: "FirstEnergy Corp.", symbol: "FE", weight: "0.053082" },
  { company: "Waters Corporation", symbol: "WAT", weight: "0.052914" },
  { company: "Tyler Technologies Inc.", symbol: "TYL", weight: "0.052762" },
  { company: "M&T Bank Corporation", symbol: "MTB", weight: "0.052103" },
  { company: "Halliburton Company", symbol: "HAL", weight: "0.051835" },
  { company: "Clorox Company", symbol: "CLX", weight: "0.051761" },
  {
    company: "Teledyne Technologies Incorporated",
    symbol: "TDY",
    weight: "0.051326",
  },
  {
    company: "Seagate Technology Holdings PLC",
    symbol: "STX",
    weight: "0.050838",
  },
  { company: "ViacomCBS Inc. Class B", symbol: "VIAC", weight: "0.050498" },
  { company: "NetApp Inc.", symbol: "NTAP", weight: "0.050489" },
  {
    company: "Broadridge Financial Solutions Inc.",
    symbol: "BR",
    weight: "0.050419",
  },
  {
    company: "Baker Hughes Company Class A",
    symbol: "BKR",
    weight: "0.050112",
  },
  { company: "PerkinElmer Inc.", symbol: "PKI", weight: "0.049744" },
  { company: "Bath & Body Works Inc.", symbol: "BBWI", weight: "0.049667" },
  { company: "Caesars Entertainment Inc", symbol: "CZR", weight: "0.049428" },
  { company: "Domino's Pizza Inc.", symbol: "DPZ", weight: "0.049326" },
  { company: "Genuine Parts Company", symbol: "GPC", weight: "0.048973" },
  { company: "Diamondback Energy Inc.", symbol: "FANG", weight: "0.048738" },
  {
    company: "Hewlett Packard Enterprise Co.",
    symbol: "HPE",
    weight: "0.048681",
  },
  { company: "Ventas Inc.", symbol: "VTR", weight: "0.048586" },
  { company: "Darden Restaurants Inc.", symbol: "DRI", weight: "0.048499" },
  { company: "Jacobs Engineering Group Inc.", symbol: "J", weight: "0.048498" },
  { company: "Cooper Companies Inc.", symbol: "COO", weight: "0.04825" },
  {
    company: "Take-Two Interactive Software Inc.",
    symbol: "TTWO",
    weight: "0.047816",
  },
  { company: "Hologic Inc.", symbol: "HOLX", weight: "0.047783" },
  {
    company: "Raymond James Financial Inc.",
    symbol: "RJF",
    weight: "0.047658",
  },
  {
    company: "Charles River Laboratories International Inc.",
    symbol: "CRL",
    weight: "0.04754",
  },
  { company: "FLEETCOR Technologies Inc.", symbol: "FLT", weight: "0.047269" },
  { company: "Healthpeak Properties Inc.", symbol: "PEAK", weight: "0.046879" },
  { company: "International Paper Company", symbol: "IP", weight: "0.046603" },
  { company: "Bio-Techne Corporation", symbol: "TECH", weight: "0.046521" },
  {
    company: "Principal Financial Group Inc.",
    symbol: "PFG",
    weight: "0.046277",
  },
  { company: "Celanese Corporation", symbol: "CE", weight: "0.046245" },
  { company: "Akamai Technologies Inc.", symbol: "AKAM", weight: "0.046046" },
  { company: "Western Digital Corporation", symbol: "WDC", weight: "0.045994" },
  {
    company: "AmerisourceBergen Corporation",
    symbol: "ABC",
    weight: "0.045965",
  },
  {
    company: "Quest Diagnostics Incorporated",
    symbol: "DGX",
    weight: "0.045794",
  },
  {
    company: "Westinghouse Air Brake Technologies Corporation",
    symbol: "WAB",
    weight: "0.045594",
  },
  { company: "Avery Dennison Corporation", symbol: "AVY", weight: "0.045484" },
  { company: "NVR Inc.", symbol: "NVR", weight: "0.045292" },
  { company: "Amcor PLC", symbol: "AMCR", weight: "0.045076" },
  {
    company: "Cincinnati Financial Corporation",
    symbol: "CINF",
    weight: "0.045036",
  },
  { company: "IDEX Corporation", symbol: "IEX", weight: "0.044974" },
  { company: "CMS Energy Corporation", symbol: "CMS", weight: "0.044479" },
  { company: "Royal Caribbean Group", symbol: "RCL", weight: "0.043322" },
  { company: "MGM Resorts International", symbol: "MGM", weight: "0.043109" },
  { company: "Coterra Energy Inc.", symbol: "CTRA", weight: "0.042957" },
  { company: "Qorvo Inc.", symbol: "QRVO", weight: "0.042684" },
  { company: "Quanta Services Inc.", symbol: "PWR", weight: "0.042657" },
  { company: "Masco Corporation", symbol: "MAS", weight: "0.042538" },
  { company: "Textron Inc.", symbol: "TXT", weight: "0.042328" },
  {
    company: "J.B. Hunt Transport Services Inc.",
    symbol: "JBHT",
    weight: "0.042237",
  },
  { company: "Boston Properties Inc.", symbol: "BXP", weight: "0.04208" },
  { company: "AES Corporation", symbol: "AES", weight: "0.041307" },
  { company: "UDR Inc.", symbol: "UDR", weight: "0.040546" },
  { company: "LKQ Corporation", symbol: "LKQ", weight: "0.040441" },
  { company: "Carnival Corporation", symbol: "CCL", weight: "0.040366" },
  { company: "Kellogg Company", symbol: "K", weight: "0.040251" },
  {
    company: "Bio-Rad Laboratories Inc. Class A",
    symbol: "BIO",
    weight: "0.039692",
  },
  { company: "Viatris Inc.", symbol: "VTRS", weight: "0.039561" },
  { company: "CenterPoint Energy Inc.", symbol: "CNP", weight: "0.039282" },
  { company: "Brown & Brown Inc.", symbol: "BRO", weight: "0.038885" },
  { company: "Eastman Chemical Company", symbol: "EMN", weight: "0.038478" },
  { company: "ABIOMED Inc.", symbol: "ABMD", weight: "0.038425" },
  { company: "Advance Auto Parts Inc.", symbol: "AAP", weight: "0.038289" },
  { company: "Ceridian HCM Holding Inc.", symbol: "CDAY", weight: "0.038096" },
  { company: "Conagra Brands Inc.", symbol: "CAG", weight: "0.038058" },
  {
    company: "United Airlines Holdings Inc.",
    symbol: "UAL",
    weight: "0.037629",
  },
  { company: "Evergy Inc.", symbol: "EVRG", weight: "0.037594" },
  { company: "Teleflex Incorporated", symbol: "TFX", weight: "0.037284" },
  {
    company: "Live Nation Entertainment Inc.",
    symbol: "LYV",
    weight: "0.037207",
  },
  { company: "Omnicom Group Inc", symbol: "OMC", weight: "0.037068" },
  { company: "Kimco Realty Corporation", symbol: "KIM", weight: "0.037046" },
  { company: "NortonLifeLock Inc.", symbol: "NLOK", weight: "0.036729" },
  {
    company: "Fortune Brands Home & Security Inc.",
    symbol: "FBHS",
    weight: "0.036511",
  },
  { company: "Whirlpool Corporation", symbol: "WHR", weight: "0.036351" },
  { company: "Alliant Energy Corp", symbol: "LNT", weight: "0.036149" },
  { company: "J.M. Smucker Company", symbol: "SJM", weight: "0.035943" },
  { company: "Cardinal Health Inc.", symbol: "CAH", weight: "0.035488" },
  { company: "CF Industries Holdings Inc.", symbol: "CF", weight: "0.035212" },
  { company: "Cboe Global Markets Inc", symbol: "CBOE", weight: "0.035013" },
  { company: "F5 Inc.", symbol: "FFIV", weight: "0.034975" },
  { company: "Iron Mountain Inc.", symbol: "IRM", weight: "0.034585" },
  { company: "Lumen Technologies Inc.", symbol: "LUMN", weight: "0.03458" },
  { company: "MarketAxess Holdings Inc.", symbol: "MKTX", weight: "0.034435" },
  { company: "PulteGroup Inc.", symbol: "PHM", weight: "0.034266" },
  {
    company: "Brown-Forman Corporation Class B",
    symbol: "BF.B",
    weight: "0.034181",
  },
  {
    company: "Interpublic Group of Companies Inc.",
    symbol: "IPG",
    weight: "0.034027",
  },
  { company: "FMC Corporation", symbol: "FMC", weight: "0.033603" },
  { company: "Marathon Oil Corporation", symbol: "MRO", weight: "0.033263" },
  { company: "Las Vegas Sands Corp.", symbol: "LVS", weight: "0.033186" },
  {
    company: "Robert Half International Inc.",
    symbol: "RHI",
    weight: "0.033107",
  },
  {
    company: "C.H. Robinson Worldwide Inc.",
    symbol: "CHRW",
    weight: "0.032455",
  },
  { company: "Pentair plc", symbol: "PNR", weight: "0.032191" },
  { company: "Hasbro Inc.", symbol: "HAS", weight: "0.032072" },
  {
    company: "Lincoln National Corporation",
    symbol: "LNC",
    weight: "0.031592",
  },
  {
    company: "American Airlines Group Inc.",
    symbol: "AAL",
    weight: "0.031556",
  },
  { company: "Incyte Corporation", symbol: "INCY", weight: "0.0315" },
  { company: "Mosaic Company", symbol: "MOS", weight: "0.031478" },
  {
    company: "Packaging Corporation of America",
    symbol: "PKG",
    weight: "0.031462",
  },
  { company: "Leidos Holdings Inc.", symbol: "LDOS", weight: "0.031348" },
  { company: "Fox Corporation Class A", symbol: "FOXA", weight: "0.031224" },
  { company: "Host Hotels & Resorts Inc.", symbol: "HST", weight: "0.031218" },
  { company: "WestRock Company", symbol: "WRK", weight: "0.031187" },
  { company: "Atmos Energy Corporation", symbol: "ATO", weight: "0.031148" },
  { company: "Tapestry Inc.", symbol: "TPR", weight: "0.030934" },
  { company: "Hormel Foods Corporation", symbol: "HRL", weight: "0.030475" },
  { company: "Comerica Incorporated", symbol: "CMA", weight: "0.030395" },
  { company: "Howmet Aerospace Inc.", symbol: "HWM", weight: "0.029747" },
  { company: "Allegion PLC", symbol: "ALLE", weight: "0.029693" },
  { company: "W. R. Berkley Corporation", symbol: "WRB", weight: "0.029358" },
  { company: "PTC Inc.", symbol: "PTC", weight: "0.029211" },
  { company: "Snap-on Incorporated", symbol: "SNA", weight: "0.029154" },
  { company: "Loews Corporation", symbol: "L", weight: "0.029123" },
  { company: "Regency Centers Corporation", symbol: "REG", weight: "0.028505" },
  {
    company: "Jack Henry & Associates Inc.",
    symbol: "JKHY",
    weight: "0.028455",
  },
  { company: "BorgWarner Inc.", symbol: "BWA", weight: "0.028375" },
  { company: "DENTSPLY SIRONA Inc.", symbol: "XRAY", weight: "0.02809" },
  { company: "Everest Re Group Ltd.", symbol: "RE", weight: "0.027782" },
  { company: "A. O. Smith Corporation", symbol: "AOS", weight: "0.02752" },
  { company: "Zions Bancorporation N.A.", symbol: "ZION", weight: "0.02743" },
  { company: "APA Corp.", symbol: "APA", weight: "0.027307" },
  { company: "Henry Schein Inc.", symbol: "HSIC", weight: "0.026589" },
  { company: "Juniper Networks Inc.", symbol: "JNPR", weight: "0.026435" },
  { company: "Citrix Systems Inc.", symbol: "CTXS", weight: "0.026338" },
  { company: "Mohawk Industries Inc.", symbol: "MHK", weight: "0.025194" },
  { company: "NiSource Inc", symbol: "NI", weight: "0.024871" },
  {
    company: "Universal Health Services Inc. Class B",
    symbol: "UHS",
    weight: "0.02452",
  },
  { company: "Sealed Air Corporation", symbol: "SEE", weight: "0.024358" },
  { company: "Wynn Resorts Limited", symbol: "WYNN", weight: "0.024242" },
  { company: "Assurant Inc.", symbol: "AIZ", weight: "0.023878" },
  { company: "Franklin Resources Inc.", symbol: "BEN", weight: "0.023727" },
  {
    company: "Federal Realty Investment Trust",
    symbol: "FRT",
    weight: "0.023145",
  },
  { company: "NRG Energy Inc.", symbol: "NRG", weight: "0.023028" },
  {
    company: "Molson Coors Beverage Company Class B",
    symbol: "TAP",
    weight: "0.022473",
  },
  { company: "Globe Life Inc.", symbol: "GL", weight: "0.021957" },
  { company: "Newell Brands Inc", symbol: "NWL", weight: "0.02195" },
  { company: "News Corporation Class A", symbol: "NWSA", weight: "0.021716" },
  { company: "PVH Corp.", symbol: "PVH", weight: "0.021234" },
  { company: "Campbell Soup Company", symbol: "CPB", weight: "0.021196" },
  {
    company: "DISH Network Corporation Class A",
    symbol: "DISH",
    weight: "0.021095",
  },
  { company: "Invesco Ltd.", symbol: "IVZ", weight: "0.020901" },
  {
    company: "Norwegian Cruise Line Holdings Ltd.",
    symbol: "NCLH",
    weight: "0.020787",
  },
  { company: "Lamb Weston Holdings Inc.", symbol: "LW", weight: "0.020365" },
  { company: "Organon & Co.", symbol: "OGN", weight: "0.020151" },
  {
    company: "People's United Financial Inc.",
    symbol: "PBCT",
    weight: "0.020135",
  },
  { company: "Rollins Inc.", symbol: "ROL", weight: "0.020129" },
  { company: "DXC Technology Co.", symbol: "DXC", weight: "0.019981" },
  { company: "Penn National Gaming Inc.", symbol: "PENN", weight: "0.019978" },
  { company: "Nielsen Holdings Plc", symbol: "NLSN", weight: "0.019061" },
  {
    company: "Pinnacle West Capital Corporation",
    symbol: "PNW",
    weight: "0.019004",
  },
  {
    company: "Huntington Ingalls Industries Inc.",
    symbol: "HII",
    weight: "0.01876",
  },
  { company: "Discovery Inc. Class C", symbol: "DISCK", weight: "0.01809" },
  { company: "Vornado Realty Trust", symbol: "VNO", weight: "0.017482" },
  { company: "DaVita Inc.", symbol: "DVA", weight: "0.017226" },
  { company: "Western Union Company", symbol: "WU", weight: "0.016926" },
  { company: "Alaska Air Group Inc.", symbol: "ALK", weight: "0.016598" },
  { company: "Hanesbrands Inc.", symbol: "HBI", weight: "0.0151" },
  { company: "IPG Photonics Corporation", symbol: "IPGP", weight: "0.014916" },
  {
    company: "Ralph Lauren Corporation Class A",
    symbol: "RL",
    weight: "0.014796",
  },
  {
    company: "Leggett & Platt Incorporated",
    symbol: "LEG",
    weight: "0.014219",
  },
  { company: "Fox Corporation Class B", symbol: "FOX", weight: "0.013345" },
  { company: "Under Armour Inc. Class A", symbol: "UAA", weight: "0.011889" },
  { company: "Under Armour Inc. Class C", symbol: "UA", weight: "0.010577" },
  { company: "Discovery Inc. Class A", symbol: "DISCA", weight: "0.010296" },
  { company: "Gap Inc.", symbol: "GPS", weight: "0.00927" },
  { company: "News Corporation Class B", symbol: "NWS", weight: "0.006909" },
  { company: "Orion Office REIT Inc.", symbol: "ONL", weight: "0.000008" },
];
